Big french review
WangDaYeeeeee/GeometricWeather pull request #228
Opened 2021-04-29 20:57 UTC by ldmpub

More to come after app test ...

2021-04-29 21:03 UTC, ldmpub commented
Thanks to come back to me for any question on these changes.

2021-05-01 12:58 UTC, Gontier-Julien commented
@ldmpub 
I think it will be better to leave `"current_location"`, `"publish_at"` and `"feedback_resident_location_description"` parts as before.
I think it would be more clear for the users.

2021-05-01 14:56 UTC, ldmpub commented
Hi,

1. For "current_location" => No problem, you can leave the previous translation.

2. For "publish_at" => It's important for users to make a clear distinction between on one hand the datetime the apps request server info and the other hand the datetime when the weather data were generated on the server side. Here my suggestion is based on the hypothesis it's the datetime of datas computed on the server side. If my hypothesis is right (server datetime displayed) then suggestion done in the translation file is accurate.

-3. Same remark as first one => No problem if you prefer "actuel(le)" instead of "courant(e)".

Waiting for your answer on point 2 😉,

2021-05-01 15:48 UTC, Gontier-Julien commented
For 1 and 3 it is not really a "preference" reason, it just seem weird saying like it for an app like this, for example it you had an app like LinkedIn it would fit. But that my opinion.

And for 2 i understand the reason behind it, and your not wrong but most weather app have it saying `Actualisé a...` and i think it fit more with the app saying it like this.

2021-05-01 22:18 UTC, ldmpub commented
Hi,

For point 2.  I'm sorry to disagree but I'm not a big fan of doing things based on "most of ..." (I prefer thinking rather than copying). In this particular case I can suggest to translate 'publish_at' by "Calculé à" which prevents confusion between 'last requested' datetime and 'last computed' datetime. I can also suggest other translations.

For 1 and 3. my opinion is that the adjective "actuelle" is more appropriate to qualify something which will change with time (actuel means now) and "courante" is more appropriate to qualify something which will change with movement like a GPS position (in french "courir" means running, it implies a movement).
Take a look at the origin and links between these 2 french words here (courant / courir): https://www.cnrtl.fr/etymologie/courant). If french is your mother tongue (like me), I may suggest to follow this discussion in french to clarify our respective opinions.

Waiting for your answers,

2021-05-02 10:07 UTC, Gontier-Julien commented
I'm also french hahahha
But yeah i get your point for 2, but making it `Calculé à (date)` it seem really weird to me, because it not going to calculate the weather🤔
But for 1 and 3, `courante` can totally be used, but like the location is taken at a certain point so for me being it `actuel` seem more appropriate.

2021-05-02 10:36 UTC, ldmpub commented
Bonjour,

**Actuel ou Courant ?**
Je privilégie l'usage de l’adjectif "actuel "pour qualifier quelque chose qui va évoluer prioritairement en fonction du temps et "courant" pour qualifier quelque chose qui va évoluer prioritairement en fonction de l'emplacement. Ce distinguo est subtile et comme une position GPS évolue surtout en fonction d'un déplacement (il est possible de rester longtemps au même endroit), je suggère d'utiliser "courant" pour améliorer la traduction.

**Traduction de "publish_at"**
J'ai expliqué plus haut (en anglais) qu'il est essentiel pour une bonne compréhension par l'utilisateur de distinguer dans l'application la date / heure de la prévision (les prévisions sont souvent faites 2 fois par jour) de la date d'interrogation du service de prévision (qui lui peut être beaucoup plus fréquent selon les actions de l'utilisateur ou le paramétrages de l'application).
C'est pourquoi j'ai proposé "Publié à" (c'est l'heure de "publication" du bulletin météo) ou encore "Calculé à" (car une prévision est majoritaire calculée par un ensemble de systèmes informatiques). Si tu as d'autres suggestions, je suis preneur. Note : j'avais pensé à (et écarté) : "généré à" (trop obscure) ou "mis en ligne à" (trop long).

Dans l'attente de tes réponses, cordialement,

2021-05-02 12:25 UTC, Gontier-Julien commented
Re,

J'ai regardé avec d'autres personnes par rapport à cela, utilise le mot actuel pour la position GPS semble être largement privilégiez.

Pour se qui est de ’publish_at’ je pense que l'on peut effectivement rester sur ’Publié à’.

2021-05-02 18:10 UTC, ldmpub commented
re-bonjour,

Ok pour `Publié à`.

Concernant le débat actuel / courant pour la position, je ne sais pas avec qui tu as échangé. Cela aurait été bien qu'ils donnent leur avis ici publiquement (plutôt qu'en "backoffice").

Par ailleurs c'est amusant car je viens d'avoir à faire à l'instant la même traduction dans une autre application (Geokrety sur Crowdin) et la suggestion automatique est de reproduire une traduction conforme à ma suggestion et qui est vieille de 9 mois :
![image](https://user-images.githubusercontent.com/1452146/116822830-634c2e80-ab81-11eb-84fc-9c0c96578cca.png)

Autre sujet : sais-tu qui peut valider cette "merge request" ? As-tu les droits de le faire ? Sinon sais-tu qui les a ?

2021-05-02 18:39 UTC, Gontier-Julien commented
Re,
J'ai demander a plusieurs amis, qui peuvent être du coup des users, et pour eux la logique est aussi d'avoir en possition actuelle.

And concerning the merge request it is only @WangDaYeeeeee that can do it.

2021-05-02 19:14 UTC, ldmpub commented
Ok thanks for your reply.

I suggest the following actions plan:
1. @WangDaYeeeeee can you please merge this pull request?
2. Then @Gontier-Julien will add the desired change through a new pull request.

I'm not very familiar with github (most of my contributions to translations are done via translation tools like Weblate, Crowdin, Transifex ...), so tell me if there's a better way to handle these changes?

2021-05-02 20:04 UTC, Gontier-Julien commented
No problem,

I will first make the desire changes to your previous pull request and then @WangDaYeeeeee can merge it.
There is no need to make two separate pull request for it.

And no worry i'm still learning things here and there also ^^
And i don't really unfortunately haha ^^'

2021-05-02 20:16 UTC, Gontier-Julien requested changes
Modification pending and in progress.

2021-05-03 11:36 UTC, papjul commented
@ldmpub I REALLY REALLY don't appreciate this way of doing things behind my back. You contacted me by email, I already told you NOT to change some things in this translation, and now you're asking to merge these changes without ever mentionning me? I spent a lot of time improving and refining this app, and agreed to change things to the translation when it was justified. Things need to be discussed in draft altogether before being pushed out of nowhere!!

Switching to French…

`current_location` => je propose "Ma position" (utilisé dans Firefox). Il faudrait peut-être mettre en concordance les autres termes.
`live` => je propose "Maintenant" (utilisé sur Météo France)
`today` => non, on ne met pas de . ou alors il faudrait changer ça également dans les colonnes avec les jours lun, mar, mer, etc, pour être cohérent. Dans un espace limité, c’est franchement inutile.
`refresh_at` => c’est inutilement long et y a une faute d’orthographe
`time` => non, je t’ai déjà expliqué, ce n’est pas utilisé aujourd’hui, et le jour où ça le sera, on ne connaît pas le contexte, donc il vaut mieux ne pas changer
`wind_level` => OK
`publish_at` => Non, j’avais vérifié, c’est la date d’actualisation, pas la date de publication
`ceiling` => OK, parce que tu es têtu, mais je t'ai déjà dit que ce n'était pas faux et on dit bien "plafond" tout seul dans le contexte météorologique https://fr.wikipedia.org/wiki/Plafond_(m%C3%A9t%C3%A9orologie)
`get_more_store` => non, pourquoi ?
`refresh` => oui, c'est mieux
`tomorrow` => non, même remarque que pour today
`feedback_get_weather_failed` => oui
`feedback_add_location_manually` => non, tout le reste est au vouvoiement, il faut être cohérent. Si d'autres termes ne sont pas au vouvoiement (hors "titres de section"), ils peuvent être corrigés.
`feedback_refresh_notification_after_back` => oui
`feedback_refresh_ui_after_refresh` => oui
`feedback_restart` => oui
`feedback_readd_location_after_changing_source` => oui
`feedback_unusable_geocoder` => oui
`feedback_resident_location_description` => Geometric Weather affichera et masquera automatiquement les villes de résidence selon votre position.\nPar exemple, vous pouvez définir votre domicile comme ville de résidence. Vous pouvez vérifier la météo à votre domicile tout en étant en déplacement. De retour chez vous, la météo à votre domicile sera cachée et remplacée par la météo de votre position.
`content_des_no_precipitation` => non, pourquoi ? Météo France utilise "Pas de précipitations", je trouve ça plus adapté au contexte.
`content_des_add_current_location` => Ajouter ma position
`content_des_drag_flag` => OK mais "déplacer" à changer en "déplacez"
`content_desc_search_filter_on` => OK mais mauvaise apostrophe + faute d’orthographe… => N’afficher
`action_settings` => pourquoi pas
`wait_refresh` => oui, c'est mieux, mais je ne sais pas où ça s'affiche, j'espère qu'il y a suffisamment de place
`settings_title_background_free` => oui mais corriger l’apostrophe
`settings_summary_background_free_on` => oui, mais problèmes de typo => Oui\nSi les widgets et notifications ne s’actualisent pas automatiquement, merci de basculer cette option à « Non ».
`settings_summary_background_free_off` => pareil => Non\nSi vous ne souhaitez pas que des services continuent à s’exécuter en arrière-plan, merci de basculer cette option à « Oui ».
`settings_summary_service_provider` => oui pour le vouvoiement, mais le terme correct est géolocalisation
`settings_title_location_service` => pareil c'est géolocalisation
`settings_title_exchange_day_night_temp_switch` => ok, je sais pas où c'est, j'imagine que tu as regardé
`settings_summary_unit` => oui
`settings_title_click_widget_to_refresh` => OK pour "Actualiser" (Actualisez ?), je suis plus sceptique pour "par appui"

2021-05-03 11:43 UTC, papjul requested changes
`current_location` => je propose "Ma position" (utilisé dans Firefox). Il faudrait peut-être mettre en concordance les autres termes.
`live` => je propose "Maintenant" (utilisé sur Météo France)
`today` => non, on ne met pas de . ou alors il faudrait changer ça également dans les colonnes avec les jours lun, mar, mer, etc, pour être cohérent. Dans un espace limité, c’est franchement inutile.
`refresh_at` => non, c’est inutilement long et y a une faute d’orthographe
`time` => non, je t’ai déjà expliqué, ce n’est pas utilisé aujourd’hui, et le jour où ça le sera, on ne connaît pas le contexte, donc il vaut mieux ne pas changer
`wind_level` => OK
`publish_at` => Non, j’avais vérifié, c’est la date d’actualisation, pas la date de publication
`ceiling` => OK, parce que tu es têtu, mais je t'ai déjà dit que ce n'était pas faux et on dit bien "plafond" tout seul dans le contexte météorologique https://fr.wikipedia.org/wiki/Plafond_(m%C3%A9t%C3%A9orologie)
`get_more_store` => non, pourquoi ?
`refresh` => oui, c'est mieux
`tomorrow` => non, même remarque que pour today
`feedback_get_weather_failed` => oui
`feedback_add_location_manually` => non, tout le reste est au vouvoiement, il faut être cohérent. Si d'autres termes ne sont pas au vouvoiement (hors "titres de section"), ils peuvent être corrigés.
`feedback_refresh_notification_after_back` => oui
`feedback_refresh_ui_after_refresh` => oui
`feedback_restart` => oui
`feedback_readd_location_after_changing_source` => oui
`feedback_unusable_geocoder` => oui
`feedback_resident_location_description` => Geometric Weather affichera et masquera automatiquement les villes de résidence selon votre position.\nPar exemple, vous pouvez définir votre domicile comme ville de résidence. Vous pouvez vérifier la météo à votre domicile tout en étant en déplacement. De retour chez vous, la météo à votre domicile sera cachée et remplacée par la celle de votre position.
`content_des_no_precipitation` => non, pourquoi ? Météo France utilise "Pas de précipitations", je trouve ça plus adapté au contexte.
`content_des_add_current_location` => Ajouter ma position
`content_des_drag_flag` => OK mais "déplacer" à changer en "déplacez"
`content_desc_search_filter_on` => OK mais mauvaise apostrophe + faute d’orthographe… => N’afficher
`action_settings` => pourquoi pas
`wait_refresh` => oui, c'est mieux, mais je ne sais pas où ça s'affiche, j'espère qu'il y a suffisamment de place
`settings_title_background_free` => oui mais corriger l’apostrophe
`settings_summary_background_free_on` => oui, mais problèmes de typo => Oui\nSi les widgets et notifications ne s’actualisent pas automatiquement, merci de basculer cette option à « Non ».
`settings_summary_background_free_off` => pareil => Non\nSi vous ne souhaitez pas que des services continuent à s’exécuter en arrière-plan, merci de basculer cette option à « Oui ».
`settings_summary_service_provider` => oui pour le vouvoiement, mais le terme correct est géolocalisation
`settings_title_location_service` => pareil c'est géolocalisation
`settings_title_exchange_day_night_temp_switch` => ok, je sais pas où c'est, j'imagine que tu as regardé
`settings_summary_unit` => oui
`settings_title_click_widget_to_refresh` => OK pour "Actualiser" (Actualisez ?), je suis plus sceptique pour "par appui", je préférerais qu’on laisse comme avant

2021-05-03 12:43 UTC, Gontier-Julien commented
Bonjour @papjul ,
Je n'étais pas au courant de tous cela.
Après il faut regarde cela avec @ldmpub qui a fait la pull request de base.
Je suis juste venue donné mon avis sur la pull request.

2021-05-03 12:56 UTC, papjul commented
@Gontier-Julien Oui, oui, pas de soucis avec toi, c’est très bien que plusieurs personnes donnent leur avis, mon message était adressé à @ldmpub avec qui j’avais déjà eu plusieurs échanges par mail donc qui me connaissait. C’est très bien de proposer des améliorations à la traduction, mais il y a aussi beaucoup de régressions qui ont été introduites donc c’est mieux d’en discuter dans une _issue_ ou une _pull request draft_ avant de demander son _merge_…

2021-05-03 13:32 UTC, Gontier-Julien commented
Oui tous a fait logique je comprends 👍

2021-05-03 21:24 UTC, papjul requested changes
D’où sort ce "(Geometric)" dans `app_name` ? Il vaut mieux que tu renommes l’application depuis ton launcher Android sans l’imposer aux autres ;)

2021-05-03 21:31 UTC, papjul requested changes
`refresh_at` Le terme "service" ne convient pas, on appelle ça "fournisseur" partout ailleurs. Cette proposition est aussi trop "lourde" comme je l’ai déjà dit, "Consulté à" va très bien.

`get_more` Quelle homogénéité ? On ne parle pas de la même chose, on se rend dans un magasin et sur un site web, l’inverse ne marche dans aucun cas (sur un magasin et dans un site web).

`week` pourquoi ? Aucune langue ne met ces points, ils prennent un caractère pour rien

2021-05-03 21:50 UTC, ldmpub commented
> `get_more` Quelle homogénéité ? On ne parle pas de la même chose, on se rend dans un magasin et sur un site web, l’inverse ne marche dans aucun cas (sur un magasin et dans un site web).

Il ne s'agit pas d'aller dans un magasin (physique) mais d'ouvrir une application / une solution informatique. Je vais sur Internet ou sur l'application X / sur la page d'accueil ...


> `week` pourquoi ? Aucune langue ne met ces points, ils prennent un caractère pour rien

un mot abrégé se termine par un point (pour le distinguer d'un mot complet), règle présentée ici par exemple : http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3401

2021-05-03 22:14 UTC, papjul commented
> > `get_more` Quelle homogénéité ? On ne parle pas de la même chose, on se rend dans un magasin et sur un site web, l’inverse ne marche dans aucun cas (sur un magasin et dans un site web).
> 
> Il ne s'agit pas d'aller dans un magasin (physique) mais d'ouvrir une application / une solution informatique. Je vais sur Internet ou sur l'application X / sur la page d'accueil ...

Personne n’a parlé de magasin physique, ni d’application ou solution informatique. On a parlé du magasin de produits. Si ça peut t’aider à comprendre, tu peux imaginer que le mot "magasin" signifie ici "catalogue". Tu peux retrouver l’application dans le catalogue, pas sur le catalogue.

Exemples :
![image](https://user-images.githubusercontent.com/1449159/116938832-40924680-ac63-11eb-8bfd-f76ce61ec835.png)

Et les quelques cas d'usage avec "sur" n'ont rien à voir avec notre cas dans leur contexte :
![image](https://user-images.githubusercontent.com/1449159/116938958-6cadc780-ac63-11eb-8841-cc4813df9f33.png)

Il est quand même possible que quelques personnes disent "mon appli se trouve sur le magasin d'applications" mais ça n’est franchement pas syntaxiquement correct… Si on commence à passer des heures à débattre sur des évidences, on va pas s’en sortir…

> > `week` pourquoi ? Aucune langue ne met ces points, ils prennent un caractère pour rien
> 
> un mot abrégé se termine par un point (pour le distinguer d'un mot complet), règle présentée ici par exemple : http://bdl.oqlf.gouv.qc.ca/bdl/gabarit_bdl.asp?id=3401

OK, mais l’appli a pas été prévue pour, donc je demande quand même à voir le rendu, et si c’est correct, il faudra répercuter le changement en anglais. Car on sort un peu du cadre de la traduction là.

2021-05-09 08:37 UTC, ldmpub commented
> 
> 
> D’où sort ce "(Geometric)" dans `app_name` ? Il vaut mieux que tu renommes l’application depuis ton launcher Android sans l’imposer aux autres ;)

Lorsqu’un utilisateur installe plusieurs applications météo, il faut qu'il puisse les distinguer par leur nom (tu peux me faire part de tes suggestions pour nommer cette appli?).
Par ailleurs je n'ai pas connaissance de cette possiblité de "renommer une application dans le launcher", est-ce une fonctionnalité introduite dans les versions récentes d'Android ?

2021-05-09 08:55 UTC, ldmpub commented
> Personne n’a parlé de magasin physique, ni d’application ou solution informatique. On a parlé du magasin de produits. Si ça peut t’aider à comprendre, tu peux imaginer que le mot "magasin" signifie ici "catalogue". Tu peux retrouver l’application dans le catalogue, pas sur le catalogue.
> 
> Exemples :
> ![image](https://user-images.githubusercontent.com/1449159/116938832-40924680-ac63-11eb-8bfd-f76ce61ec835.png)
> 
> Et les quelques cas d'usage avec "sur" n'ont rien à voir avec notre cas dans leur contexte :
> ![image](https://user-images.githubusercontent.com/1449159/116938958-6cadc780-ac63-11eb-8841-cc4813df9f33.png)

Je n'ai pas compris le sens de tes copies écran de résultats google, peux-tu m'expliquer ?

2021-05-09 11:08 UTC, ldmpub commented
New Commit done => see file attached with answers to each point raised in the above discussion (document is in french).
[Traduction Geometric Weather.odt](https://github.com/WangDaYeeeeee/GeometricWeather/files/6447337/Traduction.Geometric.Weather.odt)

2021-05-09 16:52 UTC, papjul requested changes
> > D’où sort ce "(Geometric)" dans `app_name` ? Il vaut mieux que tu renommes l’application depuis ton launcher Android sans l’imposer aux autres ;)
> 
> Lorsqu’un utilisateur installe plusieurs applications météo, il faut qu'il puisse les distinguer par leur nom (tu peux me faire part de tes suggestions pour nommer cette appli?).

Je ne sais pas pour quelle raison tu as sur ton téléphone plusieurs applications météo qui s’appellent toutes Météo ? Combien ? Si c’est 2 applications, tu dois pouvoir les différencier par l’icône. Perso, sur mon téléphone, j'ai 1 application "Fichiers", "Contacts", "Appareil photo", etc. Pourquoi aurais-je 3 applications Contacts ? Appeler une application par un terme simple compréhensible est la recommandation en terme d'expérience utilisateur. Par ailleurs si tu rallonges le nom de l’application, elle va se retrouver tronquée. De toute façon, ce n'est pas un sujet de traduction, donc ce n'est pas à débattre ici, puisqu'il n’y a pas de sens à changer spécifiquement pour le français et pas pour les autres langues.

> > `refresh_at` Le terme "service" ne convient pas, on appelle ça "fournisseur" partout ailleurs. Cette proposition est aussi trop "lourde" comme je l’ai déjà dit, "Consulté à" va très bien.
> 
> Il faudrait effectivement clarifier ce qu'on souhaite appeler 'service' et 'fournisseur' sachant que j'ai aussi vu dans l'appli la phrase "Fournisseur de service". Concernant la proposition simple "Consulté à", j'ai présenté mon point de vue ici : [#228 (comment)](https://github.com/WangDaYeeeeee/GeometricWeather/pull/228#issuecomment-830787400) => la traduction actuelle comme ta remarque ne prennent pas en compte ce point. Enfin faire court est tout à fait légitime (et c'est aussi ma préoccupation) mais il ne faut pas que cela soit au détriment du sens ce qui va inévitablement poser problème à l'utilisation.

Tu m’avais dit que tu trouvais ça trop technique "Interrogé" et j’étais d’accord avec toi, maintenant tu reviens dessus. Par ailleurs, je le répète mais ce n’est pas la date de publication du bulletin, mais la date à laquelle l'utilisateur a demandé à consulter la météo (la date de publication étant égale ou antérieure).


> Je n'ai pas compris le sens de tes copies écran de résultats google, peux-tu m'expliquer ?

Je te montre juste par des extraits d’autres sites web que « dans un magasin d’applications » se dit mais que « sur un magasin d’applications » ne se dit pas (pas dans ce sens-là en tout cas).


> feedback_resident_location_description

OK pour « affichera ou masquera », c'est effectivement mieux.

> content_des_no_precipitation => non, pourquoi ? Météo France utilise "Pas de précipitations", je trouve ça plus adapté au contexte => un mot au lieu de 2

C’est pareil en terme de place. « Aucune » est pour moi plus utilisé dans un contexte quantifiable, tu ne dirais pas « il y a 2 précipitations » par exemple, donc « pas de » est plus adapté, j’aimerais donc qu’on laisse comme ce qui se fait ailleurs.


> content_desc_search_filter_on => OK mais mauvaise apostrophe + faute d’orthographe… => N’afficher => je ne suis pas certain de bien comprendre : pour les apostrophes ’ (j’utilise mon clavier, si besoin tu peux faire un « rechercher / remplacer » global). Sinon je ne vois pas de fôtes d’haurtograffes.

Tu as mis trois F et tu as utilisé l’apostrophe dactylographique au lieu de l’apostrophe typographique. Sur tout le reste de la traduction, j’ai pris le soin de mettre les bonnes apostrophes, j’aimerais que ça le reste ainsi. Je t’ai aussi mis « N’afficher », tu n’as plus qu’à copier/coller.


> settings_title_background_free => oui mais corriger l’apostrophe => Ok à toi de jouer (cf plus haut 😉)

C’est la même apostrophe : ’

Je n’ai pas la main sur tes commits.


> settings_title_location_service => pareil c'est géolocalisation => j’aime bien les mots courts et peu nombreux quand ils n’introduisent pas de confusion.

C’est le terme français, employé déjà par d’autres applications, on ne va pas réécrire la langue xD https://fr.wikipedia.org/wiki/G%C3%A9olocalisation


> settings_title_click_widget_to_refresh => OK pour "Actualiser" (Actualisez ?), je suis plus sceptique pour "par appui", je préférerais qu’on laisse comme avant => « Actualiser » c’est bien car ce n’est pas une action « présente » mais une action future.
> « appui » : l’ancienne formulation était lourde et je ne vois pas bien une phrase du type « appuyer dessous » donc « en appuyant dessus » est un pléonasme au même titre que « monter en haut » (à la rigueur ça pourrait se justifier s’il y avait des cas d’ « appuyer vers le bas »).

Appuyer pour actualiser

2021-05-27 06:20 UTC, papjul commented
Any news on the requested changes?

2021-05-27 07:11 UTC, ldmpub commented
Don't worry I do not forget it! I just have no time yet and find the "process" to have discussions trough a text file very unfriendly 😊.

2021-07-09 10:39 UTC, merged